version: "3.9"
services:
  splunk:
    container_name: splunk
    image: splunk/splunk:8.2.2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunkpw
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
    ports:
      - "8000:8000" # management
      - "8088:8088" # http event collector port.

volumes:
  splunk_var:
  splunk_etc:
